### PR TITLE
Add feature test for child workflow results

### PR DESCRIPTION
**Pull request by Quinn-With-Two-Ns**
## What was changed
Added a feature test for child workflow results. Removed the execute readme because it overlapped with this feature.

## Checklist

1. Closes 

2. How was this tested:

3. Any docs updates needed?

### CODE REVIEW

**Comment by Sushisource** [comment]
Would be good to add a README for this feature

**Review by Sushisource — APPROVED** [review]
LGTM, just the README to add to stay consistent.

**Comment by Quinn-With-Two-Ns** [comment]
> Would be good to add a README for this feature

There already is a readme for this feature https://github.com/temporalio/sdk-features/tree/main/features/child_workflow/result

Is there other detail you'd want me to add

**Comment by Sushisource** [comment]
Oh, derp lol :face_with_spiral_eyes: -- I just thought it wasn't there since I didn't see it in the diff

**Pull request merged**
